In [1]:
import csv
import numpy as np
from numpy import array
from numpy.linalg import matrix_rank
count = 0
features_list = []
features_list2 = []
with open( "question-2-train-features.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=",", quotechar=" ")

          for vector in hop:
                i = 0
                while(i < 8):
                    value2=vector[i].replace(',', '.')
                    features_list.append(float(value2))
                    features_list2.append(vector[i])
                    i = i + 1
                    
features_list = np.reshape(features_list, (14000,8))
len(features_list)


14000

In [2]:
count = 0
features_test_list = []
features_test_list2 = []
with open( "question-2-test-features.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=",", quotechar=" ")

          for vector in hop:
                i = 0
                while(i < 8):
                    value2=vector[i].replace(',', '.')
                    features_test_list.append(float(value2))
                    features_test_list2.append(vector[i])
                    i = i + 1
                    
features_test_list = np.reshape(features_test_list, (3378,8))
print(features_test_list[2][6])
print(features_test_list2[2])

0.46
6.000000000000000000e+00


In [3]:
count = 0
labels_list = []
labels_list2 = []
with open( "question-2-train-labels.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=" ")

          for vector in hop:
                value2=vector[0].replace(',', '.')
                labels_list.append(float(value2))
                labels_list2.append(vector[0])
        
labels_list = np.array(labels_list)

print(labels_list[2])
print(labels_list2[2])

13.0
1.300000000000000000e+01


In [4]:
count = 0
labels_test_list = []
labels_test_list2 = []
with open( "question-2-test-labels.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=" ")

          for vector in hop:
                value2=vector[0].replace(',', '.')
                labels_test_list.append(float(value2))
                labels_test_list2.append(vector[0])
            
print(labels_test_list[2])
print(labels_test_list2[2])

531.0
5.310000000000000000e+02


In [5]:
from copy import copy, deepcopy
i = 0
fold = []
hop = []
hopl = []
label_fold = []
fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[0] = features_list[1400:14000]#0
label_fold[0] = labels_list[1400:14000]#0
hop[0] = features_list[0:1400]#0
hopl[0] = labels_list[0:1400]#0


fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[1] = np.append(features_list[0:1400], features_list[2800:14000])
fold[1]  = np.reshape(fold[1] , (12600,8))
label_fold[1] = np.append(labels_list[0:1400], labels_list[2800:14000])
hop[1] = features_list[1400:2800]#0
hopl[1] = labels_list[1400:2800]#0


fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[2] = np.append(features_list[0:2800], features_list[4200:14000])
fold[2]  = np.reshape(fold[2] , (12600,8))
label_fold[2] = np.append(labels_list[0:2800], labels_list[4200:14000])
hop[2] = features_list[2800:4200]#0
hopl[2] = labels_list[2800:4200]#0



fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[3] = np.append(features_list[0:4200], features_list[5600:14000])
fold[3]  = np.reshape(fold[3] , (12600,8))
label_fold[3] = np.append(labels_list[0:4200], labels_list[5600:14000])
hop[3] = features_list[4200:5600]#0
hopl[3] = labels_list[4200:5600]#0



fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[4] = np.append(features_list[0:5600], features_list[7000:14000])
fold[4]  = np.reshape(fold[4] , (12600,8))
label_fold[4] = np.append(labels_list[0:5600], labels_list[7000:14000])
hop[4] = features_list[5600:7000]#0
hopl[4] = labels_list[5600:7000]#0


fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[5] = np.append(features_list[0:7000], features_list[8400:14000])
fold[5]  = np.reshape(fold[5] , (12600,8))
label_fold[5] = np.append(labels_list[0:7000], labels_list[8400:14000])
hop[5] = features_list[7000:8400]#0
hopl[5] = labels_list[7000:8400]#0


fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[6] = np.append(features_list[0:8400], features_list[9800:14000])
fold[6]  = np.reshape(fold[6] , (12600,8))
label_fold[6] = np.append(labels_list[0:8400], labels_list[9800:14000])
hop[6] = features_list[8400:9800]#0
hopl[6] = labels_list[8400:9800]#0


fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[7] = np.append(features_list[0:9800], features_list[11200:14000])
fold[7]  = np.reshape(fold[7] , (12600,8))
label_fold[7] = np.append(labels_list[0:9800], labels_list[11200:14000])
hop[7] = features_list[9800:11200]#0
hopl[7] = labels_list[9800:11200]#0


fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[8] = np.append(features_list[0:11200], features_list[12600:14000])
fold[8]  = np.reshape(fold[8] , (12600,8))
label_fold[8] = np.append(labels_list[0:11200], labels_list[12600:14000])
hop[8] = features_list[11200:12600]#0
hopl[8] = labels_list[11200:12600]#0


fold.append([])
hop.append([])
hopl.append([])
label_fold.append([])
fold[9] = features_list[0:12600]#0
label_fold[9] = labels_list[0:12600]#0
hop[9] = features_list[12600:14000]#0

hopl[9] = labels_list[12600:14000]#0


In [45]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
scaler = StandardScaler()
i = 0
while i < 10:
    print("i th trial : ")
    scaler.fit(fold[i])
    clf = LinearSVC(C = 10 ** -3, max_iter = 2000)
    clf.fit(fold[i], label_fold[i])
    model = clf.predict(hop[i])
    print(clf.predict(hop[i]))
    print("LSVC Accuracy :", accuracy_score(hopl[i], model))
    i = i + 1

i th trial : 
[  2.   2.   2. ... 106. 106. 106.]
LSVC Accuracy : 0.030714285714285715
i th trial : 
[95. 95. 95. ... 62. 62. 62.]
LSVC Accuracy : 0.02
i th trial : 
[ 62.  62.  62. ... 123. 123. 123.]
LSVC Accuracy : 0.02
i th trial : 
[95.  5.  5. ...  5.  5.  5.]
LSVC Accuracy : 0.015714285714285715
i th trial : 
[4. 6. 6. ... 4. 4. 4.]
LSVC Accuracy : 0.015714285714285715
i th trial : 
[6. 6. 6. ... 6. 6. 6.]
LSVC Accuracy : 0.012857142857142857
i th trial : 
[  5.   6. 114. ...   7.   7.   7.]
LSVC Accuracy : 0.017142857142857144
i th trial : 
[  7.  95.  95. ... 152. 152. 152.]
LSVC Accuracy : 0.017857142857142856
i th trial : 
[152. 190.   5. ...   5.   5.   5.]
LSVC Accuracy : 0.01
i th trial : 
[ 5.  5.  5. ... 26. 26. 26.]
LSVC Accuracy : 0.011428571428571429


In [46]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

scaler = StandardScaler()
i = 0
while i < 10:
    print("i th trial : ")
    scaler.fit(fold[i])
    clf = LinearSVC(C = 10 ** -2, max_iter = 2000)
    clf.fit(fold[i], label_fold[i])
    model = clf.predict(hop[i])
    print(clf.predict(hop[i]))
    print("LSVC Accuracy :", accuracy_score(hopl[i], model))
    i = i + 1

i th trial : 
[ 2.  2.  2. ... 85. 85. 85.]
LSVC Accuracy : 0.03428571428571429
i th trial : 
[84. 84. 83. ... 36. 36. 36.]
LSVC Accuracy : 0.019285714285714285
i th trial : 
[ 36.  36.  75. ... 148. 148. 148.]
LSVC Accuracy : 0.014285714285714285
i th trial : 
[148.   5.   6. ...   6.   5.   6.]
LSVC Accuracy : 0.023571428571428573
i th trial : 
[6. 6. 6. ... 4. 4. 4.]
LSVC Accuracy : 0.015
i th trial : 
[ 4.  4. 24. ... 24. 24. 24.]
LSVC Accuracy : 0.015714285714285715
i th trial : 
[75. 75. 75. ...  2.  2.  2.]
LSVC Accuracy : 0.02142857142857143
i th trial : 
[  4.   4.  20. ... 145. 152. 152.]
LSVC Accuracy : 0.016428571428571428
i th trial : 
[148. 148.   6. ...   5.   5.   5.]
LSVC Accuracy : 0.012857142857142857
i th trial : 
[  6.   6.   6. ... 148. 174. 174.]
LSVC Accuracy : 0.012142857142857143


In [6]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

scaler = StandardScaler()
i = 0
while i < 10:
    print("i th trial : ")
    scaler.fit(fold[i])
    clf = LinearSVC(C = 10 ** -1, max_iter = 200)
    clf.fit(fold[i], label_fold[i])
    model = clf.predict(hop[i])
    print(clf.predict(hop[i]))
    print("LSVC Accuracy :", accuracy_score(hopl[i], model))    
    i = i + 1

i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[  2.   2.   2. ... 250. 250. 250.]
LSVC Accuracy : 0.03357142857142857
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[702. 702. 702. ... 458. 458. 458.]
LSVC Accuracy : 0.019285714285714285
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[458. 458. 458. ... 749. 749. 749.]
LSVC Accuracy : 0.011428571428571429
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[957. 957. 957. ... 957. 957. 957.]
LSVC Accuracy : 0.0
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[685. 685. 685. ... 685. 685.   4.]
LSVC Accuracy : 0.004285714285714286
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[749. 749. 749. ... 749. 749. 749.]
LSVC Accuracy : 0.0
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[153. 153. 153. ...   2.   2. 153.]
LSVC Accuracy : 0.018571428571428572
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[  4.   4.   4. ... 180. 180. 180.]
LSVC Accuracy : 0.012857142857142857
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[522. 522.   6. ... 536. 536. 536.]
LSVC Accuracy : 0.014285714285714285
i th trial : 
[746. 746. 746. ... 746. 746. 746.]
LSVC Accuracy : 0.0014285714285714286


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [7]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

scaler = StandardScaler()
i = 0
while i < 10:
    print("i th trial : ")
    scaler.fit(fold[i])
    clf = LinearSVC(C = 10, max_iter = 200)
    clf.fit(fold[i], label_fold[i])
    model = clf.predict(hop[i])
    print(clf.predict(hop[i]))
    print("LSVC Accuracy :", accuracy_score(hopl[i], model))
    i = i + 1

i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[103. 103. 103. ... 182. 182. 182.]
LSVC Accuracy : 0.018571428571428572
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[133. 133. 133. ... 666. 133. 133.]
LSVC Accuracy : 0.0014285714285714286
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[666. 666. 666. ... 683. 822. 822.]
LSVC Accuracy : 0.0
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[481. 562. 752. ... 752. 562. 752.]
LSVC Accuracy : 0.0
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[757. 757. 757. ... 757. 757. 757.]
LSVC Accuracy : 0.0
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[655. 655. 655. ... 655. 655. 655.]
LSVC Accuracy : 0.0007142857142857143
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[530. 530. 530. ... 530. 530. 530.]
LSVC Accuracy : 0.0007142857142857143
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[668. 668. 668. ... 607. 607. 607.]
LSVC Accuracy : 0.0014285714285714286
i th trial : 


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[  1.   1. 757. ...   1.   1.   1.]
LSVC Accuracy : 0.0014285714285714286
i th trial : 
[698. 698. 698. ... 698. 698. 698.]
LSVC Accuracy : 0.002142857142857143


c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [ ]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

scaler = StandardScaler()
i = 0
while i < 10:
    print("i th trial : ")
    scaler.fit(fold[i])
    clf = LinearSVC(C = 10 ** 2, max_iter = 2000)
    clf.fit(fold[i], label_fold[i])
    model = clf.predict(hop[i])
    print(clf.predict(hop[i]))
    print("LSVC Accuracy :", accuracy_score(hopl[i], model))
    i = i + 1

In [22]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix

scaler = StandardScaler()
scaler.fit(features_list)
clf = LinearSVC(C = 10 ** -2, max_iter = 2000)
clf.fit(features_list, labels_list)
model = clf.predict(features_test_list)
print(clf.predict(features_test_list))
print("LSVC Accuracy :", accuracy_score(labels_test_list, model))
cnf_matrix = confusion_matrix(labels_test_list, model)
print(cnf_matrix)


[374. 374. 374. ...  62.  62.  62.]
LSVC Accuracy : 0.010657193605683837
[[0 0 2 ... 0 0 0]
 [0 0 7 ... 0 0 0]
 [0 0 6 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
scaler = StandardScaler()
scaler.fit(features_list)
clf = SVC(kernel='rbf', random_state=0, gamma=.0002, C=1)
clf.fit(features_list, labels_list)
model = clf.predict(features_test_list)
print(clf.predict(features_test_list))
print("LSVC Accuracy :", accuracy_score(labels_test_list, model))
cnf_matrix = confusion_matrix(labels_test_list, model)

[64. 64. 90. ... 64. 64. 64.]
LSVC Accuracy : 0.014801657785671996


In [10]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
scaler = StandardScaler()
scaler.fit(features_list)
clf = SVC(kernel='rbf', random_state=0, gamma=.002, C=1)
clf.fit(features_list, labels_list)
model = clf.predict(features_test_list)
print(clf.predict(features_test_list))
print("LSVC Accuracy :", accuracy_score(labels_test_list, model))
cnf_matrix = confusion_matrix(labels_test_list, model)

[106. 106. 106. ... 152. 152. 152.]
LSVC Accuracy : 0.011545293072824156


In [11]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
scaler = StandardScaler()
scaler.fit(features_list)
clf = SVC(kernel='rbf', random_state=0, gamma=.02, C=1)
clf.fit(features_list, labels_list)
model = clf.predict(features_test_list)
print(clf.predict(features_test_list))
print("LSVC Accuracy :", accuracy_score(labels_test_list, model))
cnf_matrix = confusion_matrix(labels_test_list, model)


[165. 165. 374. ...  95.  95.  95.]
LSVC Accuracy : 0.012729425695677915


In [12]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
scaler = StandardScaler()
scaler.fit(features_list)
clf = SVC(kernel='rbf', random_state=0, gamma=.2, C=1)
clf.fit(features_list, labels_list)
model = clf.predict(features_test_list)
print(clf.predict(features_test_list))
print("LSVC Accuracy :", accuracy_score(labels_test_list, model))
cnf_matrix = confusion_matrix(labels_test_list, model)

[380. 380. 302. ... 139.  45.  45.]
LSVC Accuracy : 0.014505624629958556


In [13]:
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
scaler = StandardScaler()
scaler.fit(features_list)
clf = SVC(kernel='rbf', random_state=0, gamma=2, C=1)
clf.fit(features_list, labels_list)
model = clf.predict(features_test_list)
print(clf.predict(features_test_list))
print("LSVC Accuracy :", accuracy_score(labels_test_list, model))
cnf_matrix = confusion_matrix(labels_test_list, model)

[259. 390. 373. ... 121.  27.  29.]
LSVC Accuracy : 0.012433392539964476
