In [14]:
import csv
import numpy as np
from numpy import array
from numpy.linalg import matrix_rank
count = 0
features_list = []
features_list2 = []
with open( "question-2-train-features.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=",", quotechar=" ")

          for vector in hop:
                i = 0
                while(i < 8):
                    value2=vector[i].replace(',', '.')
                    features_list.append(float(value2))
                    features_list2.append(vector[i])
                    i = i + 1
                    
features_list = np.reshape(features_list, (14000,8))
mult = (features_list.T).dot(features_list)


In [15]:
count = 0
features_test_list = []
features_test_list2 = []
with open( "question-2-test-features.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=",", quotechar=" ")

          for vector in hop:
                i = 0
                while(i < 8):
                    value2=vector[i].replace(',', '.')
                    features_test_list.append(float(value2))
                    features_test_list2.append(vector[i])
                    i = i + 1
                    
features_test_list = np.reshape(features_test_list, (3378,8))
print(features_test_list[2][6])
print(features_test_list2[2])

0.46
6.000000000000000000e+00


In [16]:
count = 0
labels_test_list = []
labels_test_list2 = []
with open( "question-2-test-labels.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=" ")

          for vector in hop:
                value2=vector[0].replace(',', '.')
                labels_test_list.append(float(value2))
                labels_test_list2.append(vector[0])
            
print(labels_test_list[2])
print(labels_test_list2[2])

531.0
5.310000000000000000e+02


In [17]:
count = 0
labels_list = []
labels_list2 = []
with open( "question-2-train-labels.csv") as csv_hop:
          hop = csv.reader(csv_hop, delimiter=" ")

          for vector in hop:
                value2=vector[0].replace(',', '.')
                labels_list.append(float(value2))
                labels_list2.append(vector[0])
            
print(labels_list[2])
print(labels_list2[2])

13.0
1.300000000000000000e+01


In [18]:
def sigmoid(result):
    final_result = 1/(1+np.exp(-result)) #There is a problem here but I could not solve it
    #print(final_result) 
    return final_result

In [19]:
def my_function(y, w, x, b):
    final_result = 0
    final_result = sigmoid(np.dot(w,x.T)+b)
    cost = (-1/14000)*(np.sum((y.T*np.log(final_result)) + ((1-y.T)*(np.log(1-final_result)))))
    dw = 0
    dw = (1/14000)*(np.dot(x.T, (final_result-y.T).T))
    db = 0
    db = (1/14000)*(np.sum(final_result-y.T))
    grads = {"dw": dw, "db": db}
    return grads, cost

In [20]:
from numpy import linalg as LA
w = np.zeros((1,8))
b = 0
print(w)
i = 0
labels_list = np.array(labels_list)
while i < 1001:
    grads, cost = my_function(labels_list, w, features_list, b)
    dw = grads["dw"]
    db = grads["db"]
    hop =  (10**-5) * (dw.T)
    w = w - hop
    b = b - ( (10**-5) * db)
    i = i + 1
    print("DW: ")
    print(dw)
    print("W: ")
    print(w)
    

[[0. 0. 0. 0. 0. 0. 0. 0.]]
DW: 
[[-1038.32739286]
 [-2485.53475   ]
 [ -532.06296429]
 [ -231.926     ]
 [ -101.99605786]
 [  -96.60396818]
 [  -98.18672143]
 [  -36.01405793]]
W: 
[[0.01038327 0.02485535 0.00532063 0.00231926 0.00101996 0.00096604
  0.00098187 0.00036014]]
DW: 
[[-1037.78994622]
 [-2484.20521111]
 [ -531.78608829]
 [ -231.79801631]
 [ -101.94904347]
 [  -96.5590952 ]
 [  -98.13231053]
 [  -35.99592635]]
W: 
[[0.02076117 0.0496974  0.01063849 0.00463724 0.00203945 0.00193163
  0.00196319 0.0007201 ]]
DW: 
[[-1037.30973489]
 [-2483.0388392 ]
 [ -531.53775142]
 [ -231.68286793]
 [ -101.90688299]
 [  -96.51884999]
 [  -98.08333168]
 [  -35.97963095]]
W: 
[[0.03113427 0.07452779 0.01595387 0.00695407 0.00305852 0.00289682
  0.00294402 0.0010799 ]]
DW: 
[[-1036.91664174]
 [-2482.11823613]
 [ -531.33317452]
 [ -231.58751344]
 [ -101.87220034]
 [  -96.4857323 ]
 [  -98.0426771 ]
 [  -35.96618479]]
W: 
[[0.04150344 0.09934897 0.0212672  0.00926994 0.00407724 0.00386168
  0.00

c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in multiply
  after removing the cwd from sys.path.


DW: 
[[-1035.49509926]
 [-2479.76124347]
 [ -530.56068062]
 [ -231.21656729]
 [ -101.74582412]
 [  -96.36440707]
 [  -97.87546313]
 [  -35.91726347]]
W: 
[[0.90103441 2.15761816 0.46167403 0.20120072 0.08853282 0.08385046
  0.08517099 0.03125352]]
DW: 
[[-1035.49505331]
 [-2479.76123756]
 [ -530.56063992]
 [ -231.21653666]
 [ -101.74581761]
 [  -96.36440058]
 [  -97.87544948]
 [  -35.91725901]]
W: 
[[0.91138936 2.18241577 0.46697963 0.20351289 0.08955027 0.08481411
  0.08614974 0.03161269]]
DW: 
[[-1035.49500961]
 [-2479.76123204]
 [ -530.56060119]
 [ -231.21650729]
 [ -101.74581139]
 [  -96.36439439]
 [  -97.8754364 ]
 [  -35.91725472]]
W: 
[[0.92174431 2.20721339 0.47228524 0.20582505 0.09056773 0.08577775
  0.0871285  0.03197186]]
DW: 
[[-1035.49496803]
 [-2479.76122686]
 [ -530.56056432]
 [ -231.21647913]
 [ -101.74580545]
 [  -96.36438846]
 [  -97.87542385]
 [  -35.91725059]]
W: 
[[0.93209926 2.232011   0.47759084 0.20813722 0.09158519 0.0867414
  0.08810725 0.03233104]]
DW: 
[[-1

DW: 
[[-1035.49402305]
 [-2479.76114401]
 [ -530.55976053]
 [ -231.2157391 ]
 [ -101.74565844]
 [  -96.36424121]
 [  -97.87509135]
 [  -35.91713557]]
W: 
[[1.80191445 4.31501037 0.92326121 0.40235862 0.17705158 0.16768739
  0.17032241 0.06250146]]
DW: 
[[-1035.49402097]
 [-2479.76114396]
 [ -530.55975918]
 [ -231.21573707]
 [ -101.74565805]
 [  -96.36424083]
 [  -97.87509041]
 [  -35.91713521]]
W: 
[[1.81226939 4.33980798 0.92856681 0.40467078 0.17806904 0.16865104
  0.17130116 0.06286063]]
DW: 
[[-1035.49401895]
 [-2479.76114391]
 [ -530.55975788]
 [ -231.21573509]
 [ -101.74565768]
 [  -96.36424045]
 [  -97.87508949]
 [  -35.91713487]]
W: 
[[1.82262433 4.3646056  0.93387241 0.40698293 0.17908649 0.16961468
  0.17227991 0.0632198 ]]
DW: 
[[-1035.49401697]
 [-2479.76114386]
 [ -530.55975662]
 [ -231.21573316]
 [ -101.74565732]
 [  -96.36424008]
 [  -97.87508859]
 [  -35.91713453]]
W: 
[[1.83297927 4.38940321 0.93917801 0.40929509 0.18010395 0.17057832
  0.17325866 0.06357897]]
DW: 
[[-

DW: 
[[-1035.49394547]
 [-2479.76114288]
 [ -530.55971875]
 [ -231.21566061]
 [ -101.74564351]
 [  -96.36422614]
 [  -97.87505399]
 [  -35.91712146]]
W: 
[[2.70279421 6.47240257 1.38484818 0.60351627 0.26557029 0.25152427
  0.25547372 0.09374936]]
DW: 
[[-1035.49394516]
 [-2479.76114288]
 [ -530.55971864]
 [ -231.2156603 ]
 [ -101.74564345]
 [  -96.36422608]
 [  -97.87505384]
 [  -35.9171214 ]]
W: 
[[2.71314915 6.49720018 1.39015378 0.60582843 0.26658775 0.25248792
  0.25645247 0.09410853]]
DW: 
[[-1035.49394487]
 [-2479.76114288]
 [ -530.55971853]
 [ -231.21565998]
 [ -101.74564339]
 [  -96.36422602]
 [  -97.87505368]
 [  -35.91712134]]
W: 
[[2.72350409 6.52199779 1.39545937 0.60814058 0.26760521 0.25345156
  0.25743122 0.0944677 ]]
DW: 
[[-1035.49394457]
 [-2479.76114288]
 [ -530.55971843]
 [ -231.21565968]
 [ -101.74564333]
 [  -96.36422596]
 [  -97.87505353]
 [  -35.91712128]]
W: 
[[2.73385903 6.5467954  1.40076497 0.61045274 0.26862266 0.2544152
  0.25840997 0.09482687]]
DW: 
[[-1

DW: 
[[-1035.49393237]
 [-2479.76114286]
 [ -530.55971486]
 [ -231.21564683]
 [ -101.7456408 ]
 [  -96.36422339]
 [  -97.87504707]
 [  -35.91711883]]
W: 
[[3.59331899 8.60499715 1.84112954 0.80236173 0.35307155 0.33439751
  0.33964626 0.12463808]]
DW: 
[[-1035.49393231]
 [-2479.76114286]
 [ -530.55971485]
 [ -231.21564676]
 [ -101.74564079]
 [  -96.36422338]
 [  -97.87504704]
 [  -35.91711882]]
W: 
[[3.60367393 8.62979476 1.84643513 0.80467389 0.354089   0.33536115
  0.34062501 0.12499725]]
DW: 
[[-1035.49393225]
 [-2479.76114286]
 [ -530.55971483]
 [ -231.2156467 ]
 [ -101.74564077]
 [  -96.36422337]
 [  -97.87504701]
 [  -35.91711881]]
W: 
[[3.61402887 8.65459237 1.85174073 0.80698604 0.35510646 0.33632479
  0.34160376 0.12535643]]
DW: 
[[-1035.49393218]
 [-2479.76114286]
 [ -530.55971482]
 [ -231.21564663]
 [ -101.74564076]
 [  -96.36422335]
 [  -97.87504697]
 [  -35.91711879]]
W: 
[[3.62438381 8.67938998 1.85704633 0.8092982  0.35612391 0.33728843
  0.34258251 0.1257156 ]]
DW: 
[[-

DW: 
[[-1035.49392977]
 [-2479.76114286]
 [ -530.5597144 ]
 [ -231.2156441 ]
 [ -101.74564025]
 [  -96.36422283]
 [  -97.87504566]
 [  -35.9171183 ]]
W: 
[[ 4.31816475 10.34082995  2.21252134  0.96421268  0.42429349  0.40185246
   0.40815879  0.14978007]]
DW: 
[[-1035.49392975]
 [-2479.76114286]
 [ -530.5597144 ]
 [ -231.21564408]
 [ -101.74564025]
 [  -96.36422283]
 [  -97.87504565]
 [  -35.9171183 ]]
W: 
[[ 4.32851968 10.36562756  2.21782693  0.96652484  0.42531095  0.40281611
   0.40913754  0.15013924]]
DW: 
[[-1035.49392973]
 [-2479.76114286]
 [ -530.5597144 ]
 [ -231.21564406]
 [ -101.74564024]
 [  -96.36422283]
 [  -97.87504564]
 [  -35.91711829]]
W: 
[[ 4.33887462 10.39042517  2.22313253  0.96883699  0.42632841  0.40377975
   0.41011629  0.15049841]]
DW: 
[[-1035.49392971]
 [-2479.76114286]
 [ -530.5597144 ]
 [ -231.21564404]
 [ -101.74564024]
 [  -96.36422282]
 [  -97.87504563]
 [  -35.91711829]]
W: 
[[ 4.34922956 10.41522278  2.22843813  0.97114915  0.42734586  0.40474339
   0

 [  -35.91711813]]
W: 
[[ 5.13620495 12.29984125  2.63166351  1.14687304  0.50467255  0.4779802
   0.48548008  0.17815459]]
DW: 
[[-1035.4939289 ]
 [-2479.76114286]
 [ -530.55971431]
 [ -231.2156432 ]
 [ -101.74564007]
 [  -96.36422265]
 [  -97.87504518]
 [  -35.91711812]]
W: 
[[ 5.14655989 12.32463886  2.63696911  1.1491852   0.50569001  0.47894384
   0.48645883  0.17851376]]
DW: 
[[-1035.4939289 ]
 [-2479.76114286]
 [ -530.55971431]
 [ -231.21564319]
 [ -101.74564007]
 [  -96.36422265]
 [  -97.87504518]
 [  -35.91711812]]
W: 
[[ 5.15691483 12.34943648  2.6422747   1.15149735  0.50670746  0.47990748
   0.48743758  0.17887293]]
DW: 
[[-1035.49392889]
 [-2479.76114286]
 [ -530.55971431]
 [ -231.21564319]
 [ -101.74564007]
 [  -96.36422265]
 [  -97.87504518]
 [  -35.91711812]]
W: 
[[ 5.16726977 12.37423409  2.6475803   1.15380951  0.50772492  0.48087113
   0.48841633  0.1792321 ]]
DW: 
[[-1035.49392889]
 [-2479.76114286]
 [ -530.5597143 ]
 [ -231.21564318]
 [ -101.74564007]
 [  -96.36422

DW: 
[[-1035.49392867]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564296]
 [ -101.74564002]
 [  -96.3642226 ]
 [  -97.87504505]
 [  -35.91711808]]
W: 
[[ 5.95424515 14.25885256  3.05080568  1.3295334   0.58505161  0.55410794
   0.56280137  0.20652911]]
DW: 
[[-1035.49392867]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564295]
 [ -101.74564002]
 [  -96.3642226 ]
 [  -97.87504505]
 [  -35.91711808]]
W: 
[[ 5.96460009 14.28365017  3.05611128  1.33184555  0.58606906  0.55507158
   0.56378012  0.20688828]]
DW: 
[[-1035.49392867]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564295]
 [ -101.74564002]
 [  -96.3642226 ]
 [  -97.87504505]
 [  -35.91711808]]
W: 
[[ 5.97495503 14.30844778  3.06141688  1.33415771  0.58708652  0.55603522
   0.56475887  0.20724745]]
DW: 
[[-1035.49392866]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564295]
 [ -101.74564002]
 [  -96.3642226 ]
 [  -97.87504505]
 [  -35.91711808]]
W: 
[[ 5.98530997 14.33324539  3.06672248  1.33646987  0.58810397  0.55699886
   0

DW: 
[[-1035.4939286 ]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564288]
 [ -101.74564001]
 [  -96.36422258]
 [  -97.87504501]
 [  -35.91711806]]
W: 
[[ 6.80335017 16.29225669  3.48586465  1.51913022  0.66848303  0.6331266
   0.6430589   0.23598115]]
DW: 
[[-1035.4939286 ]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564288]
 [ -101.74564001]
 [  -96.36422258]
 [  -97.87504501]
 [  -35.91711806]]
W: 
[[ 6.81370511 16.3170543   3.49117025  1.52144238  0.66950049  0.63409024
   0.64403765  0.23634032]]
DW: 
[[-1035.4939286 ]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564288]
 [ -101.74564001]
 [  -96.36422258]
 [  -97.87504501]
 [  -35.91711806]]
W: 
[[ 6.82406005 16.34185192  3.49647584  1.52375454  0.67051794  0.63505388
   0.6450164   0.23669949]]
DW: 
[[-1035.4939286 ]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564288]
 [ -101.74564001]
 [  -96.36422258]
 [  -97.87504501]
 [  -35.91711806]]
W: 
[[ 6.83441499 16.36664953  3.50178144  1.52606669  0.6715354   0.63601753
   0.

 [  -35.91711806]]
W: 
[[ 7.64210026 18.30086322  3.91561802  1.7064149   0.750897    0.71118162
   0.72233769  0.26507401]]
DW: 
[[-1035.49392858]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 7.6524552  18.32566083  3.92092362  1.70872705  0.75191445  0.71214526
   0.72331644  0.26543319]]
DW: 
[[-1035.49392858]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 7.66281014 18.35045844  3.92622921  1.71103921  0.75293191  0.7131089
   0.72429519  0.26579236]]
DW: 
[[-1035.49392858]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 7.67316507 18.37525605  3.93153481  1.71335136  0.75394937  0.71407255
   0.72527394  0.26615153]]
DW: 
[[-1035.49392858]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422

 [  -35.91711806]]
W: 
[[ 8.49120528 20.33426736  4.35067698  1.89601172  0.83432842  0.79020028
   0.80259523  0.29452605]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 8.50156022 20.35906497  4.35598258  1.89832388  0.83534588  0.79116392
   0.80357398  0.29488522]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 8.51191516 20.38386258  4.36128818  1.90063604  0.83636334  0.79212757
   0.80455273  0.29524439]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 8.5222701  20.40866019  4.36659378  1.90294819  0.83738079  0.79309121
   0.80553148  0.29560357]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.3642

DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 9.36102018 22.41726672  4.79634714  2.09023286  0.91979476  0.87114623
   0.88481026  0.32469643]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 9.37137512 22.44206433  4.80165274  2.09254502  0.92081222  0.87210987
   0.88578901  0.3250556 ]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 9.38173006 22.46686194  4.80695834  2.09485718  0.92182967  0.87307351
   0.88676776  0.32541477]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[ 9.392085   22.49165955  4.81226394  2.09716933  0.92284713  0.87403715
   0

DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[10.2101252  24.45067085  5.23140611  2.27982969  1.00322619  0.95016489
   0.9650678   0.35414847]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[10.22048014 24.47546846  5.23671171  2.28214185  1.00424364  0.95112853
   0.96604655  0.35450764]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[10.23083508 24.50026608  5.2420173   2.284454    1.0052611   0.95209218
   0.9670253   0.35486681]]
DW: 
[[-1035.49392857]
 [-2479.76114286]
 [ -530.55971429]
 [ -231.21564286]
 [ -101.74564   ]
 [  -96.36422258]
 [  -97.875045  ]
 [  -35.91711806]]
W: 
[[10.24119002 24.52506369  5.2473229   2.28676616  1.00627855  0.95305582
   0

In [21]:
def predict(final_pred):
    y_pred = np.zeros((1,3378))
    for i in range(final_pred.shape[1]):
        if final_pred[0][i] > 0.5:
            y_pred[0][i] = 1
    return y_pred

In [22]:
print(w)
final_test_pred = 1/(1+np.exp(-np.dot(w, features_test_list.T)+b))
y_ts_pred = predict(final_test_pred)
i = 0
while(i < 3378):
    print(y_ts_pred[0][i])
    i = i + 1


[[10.36544929 24.82263502  5.31099007  2.31451204  1.01848803  0.96461952
   0.97974906  0.35953604]]
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [80]:
from numpy import linalg as LA
w = np.zeros((1,8))
b = 0
print(w)
i = 0
labels_list = np.array(labels_list)
total_cost = 0
while i < 1001:
    j = 0
    while j < (14000 / 32):
        x_batch = features_list[(j * 32):(j*32)+32]
        y_batch = labels_list[(j * 32):(j*32)+32]
        grads, cost = my_function(y_batch, w, x_batch, b)
        dw = grads["dw"]
        db = grads["db"]
        total_cost = total_cost + cost
        hop =  1/32 * (10**-3) * (dw.T)
        w = w - hop
        b = b - 1/32 *( (10**-3) * db)
        j = j + 1
    total_cost = total_cost / 32
    i = i + 1

    print("DW: ")
    print(dw)
    print("W: ")
    print(w)


[[0. 0. 0. 0. 0. 0. 0. 0.]]
DW: 
[[-1.92020935]
 [-2.66880369]
 [-1.41099864]
 [-0.25657831]
 [-0.17484378]
 [-0.16391092]
 [-0.1570082 ]
 [-0.05251151]]
W: 
[[0.03242517 0.0776221  0.0166162  0.00724278 0.00318543 0.00301702
  0.00306624 0.00112475]]
DW: 
[[-1.91902872]
 [-2.66756738]
 [-1.41012659]
 [-0.25638585]
 [-0.17474311]
 [-0.16381733]
 [-0.15689851]
 [-0.05248537]]
W: 
[[0.06481582 0.15516247 0.03321403 0.01447695 0.00636781 0.00603113
  0.00612879 0.00224829]]
DW: 
[[-1.91843272]
 [-2.66710696]
 [-1.40968142]
 [-0.25628002]
 [-0.1746934 ]
 [-0.16377127]
 [-0.15684151]
 [-0.05247291]]
W: 
[[0.09719124 0.23267272 0.04980348 0.02170712 0.00954883 0.00904393
  0.0091896  0.00337128]]
DW: 
[[-1.91812381]
 [-2.66692615]
 [-1.40944997]
 [-0.2562216 ]
 [-0.17466798]
 [-0.16374774]
 [-0.15681151]
 [-0.05246635]]
W: 
[[0.12955982 0.31017282 0.06638911 0.02893545 0.01272925 0.01205615
  0.01224956 0.00449404]]
DW: 
[[-1.91795605]
 [-2.66685057]
 [-1.40932418]
 [-0.25618881]
 [-0.174654

c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """



[[-1.91771454]
 [-2.66678572]
 [-1.40914305]
 [-0.25614289]
 [-0.17463431]
 [-0.1637165 ]
 [-0.15677217]
 [-0.05245634]]
W: 
[[0.67968657 1.62755514 0.34826285 0.15177649 0.06678377 0.06325174
  0.06424933 0.02357599]]
DW: 
[[-1.91771446]
 [-2.66678572]
 [-1.40914298]
 [-0.25614288]
 [-0.1746343 ]
 [-0.16371649]
 [-0.15677216]
 [-0.05245633]]
W: 
[[0.71204584 1.70504769 0.36484291 0.15900204 0.06996333 0.06626314
  0.06730795 0.02469841]]
DW: 
[[-1.9177144 ]
 [-2.66678572]
 [-1.40914294]
 [-0.25614287]
 [-0.1746343 ]
 [-0.16371649]
 [-0.15677215]
 [-0.05245633]]
W: 
[[0.7444051  1.78254023 0.38142297 0.16622758 0.07314289 0.06927453
  0.07036657 0.02582083]]
DW: 
[[-1.91771436]
 [-2.66678572]
 [-1.40914292]
 [-0.25614287]
 [-0.17463429]
 [-0.16371648]
 [-0.15677215]
 [-0.05245633]]
W: 
[[0.77676435 1.86003277 0.39800301 0.17345312 0.07632245 0.07228592
  0.07342519 0.02694324]]
DW: 
[[-1.91771434]
 [-2.66678572]
 [-1.4091429 ]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677215

c:\users\pc\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in multiply
  """


DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[1.58574446 3.7973462  0.81250316 0.35409074 0.15581131 0.14757055
  0.14989025 0.05500356]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[1.61810365 3.87483874 0.82908316 0.36131623 0.15899086 0.15058193
  0.15294885 0.05612597]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[1.65046284 3.95233127 0.84566315 0.36854172 0.16217042 0.15359331
  0.15600744 0.05724838]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[1.68282203 4.02982381 0.86224314 0.37576722 0.16534997 0.1566047
  0.15906604 0.05837079]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[2.9771895  7.12952524 1.52544281 0.66478683 0.29253203 0.27705998
  0.28140987 0.1032672 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[3.00954868 7.20701777 1.5420228  0.67201231 0.29571158 0.28007137
  0.28446847 0.10438961]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[3.04190787 7.28451031 1.55860279 0.6792378  0.29889113 0.28308275
  0.28752706 0.10551202]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[3.07426705 7.36200284 1.57518278 0.68646329 0.30207068 0.28609413
  0.29058566 0.10663443]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.1567

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 4.33627528 10.38421174  2.22180244  0.96825736  0.42607318  0.40353803
   0.40987087  0.15040842]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 4.36863447 10.46170427  2.23838243  0.97548285  0.42925273  0.40654941
   0.41292947  0.15153083]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 4.40099365 10.53919681  2.25496242  0.98270834  0.43243228  0.40956079
   0.41598806  0.15265324]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 4.43335284 10.61668934  2.27154241  0.98993383  0.43561184  0.41257217
   0.41904666  0.15377565]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 5.59828351 13.40642063  2.86842209  1.25005143  0.55007568  0.52098192
   0.52915608  0.1941824 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 5.6306427  13.48391317  2.88500208  1.25727692  0.55325523  0.52399331
   0.53221468  0.19530481]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 5.66300188 13.5614057   2.90158207  1.26450241  0.55643478  0.52700469
   0.53527327  0.19642722]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 5.69536107 13.63889824  2.91816206  1.27172789  0.55961434  0.53001607
   0.53833187  0.19754963]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 6.95736929 16.66110713  3.56478171  1.55352196  0.68361683  0.64745997
   0.65761708  0.24132362]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 6.98972848 16.73859967  3.5813617   1.56074745  0.68679639  0.65047135
   0.66067568  0.24244603]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 7.02208766 16.8160922   3.59794169  1.56797294  0.68997594  0.65348273
   0.66373427  0.24356844]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 7.05444685 16.89358474  3.61452169  1.57519843  0.69315549  0.65649411
   0.66679287  0.24469085]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 8.28409589 19.83830109  4.24456135  1.849767    0.81397844  0.77092663
   0.78301948  0.28734243]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 8.31645507 19.91579363  4.26114134  1.85699249  0.81715799  0.77393801
   0.78607808  0.28846484]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 8.34881426 19.99328617  4.27772133  1.86421798  0.82033754  0.77694939
   0.78913667  0.28958725]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 8.38117344 20.0707787   4.29430132  1.87144347  0.82351709  0.77996077
   0.79219527  0.29070966]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 9.61082248 23.01549506  4.92434098  2.14601204  0.94434004  0.89439329
   0.90842188  0.33336124]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 9.64318167 23.09298759  4.94092097  2.15323753  0.94751959  0.89740467
   0.91148048  0.33448365]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 9.67554085 23.17048013  4.95750096  2.16046302  0.95069914  0.90041605
   0.91453907  0.33560606]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[ 9.70790004 23.24797267  4.97408095  2.16768851  0.95387869  0.90342743
   0.91759767  0.33672847]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[10.84047152 25.96021142  5.55438064  2.42058062  1.06516298  1.0088258
   1.0246485   0.37601281]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[10.87283071 26.03770395  5.57096063  2.42780611  1.06834254  1.01183718
   1.02770709  0.37713522]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[10.90518989 26.11519649  5.58754062  2.4350316   1.07152209  1.01484857
   1.03076569  0.37825763]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[10.93754908 26.19268902  5.60412061  2.44225709  1.07470164  1.01785995
   1.03382428  0.37938004]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.174

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[12.32899405 29.52486806  6.31706023  2.75295311  1.21142234  1.14734937
   1.16534388  0.42764367]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[12.36135323 29.60236059  6.33364022  2.7601786   1.21460189  1.15036075
   1.16840247  0.42876608]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[12.39371242 29.67985313  6.35022021  2.76740408  1.21778144  1.15337214
   1.17146107  0.42988849]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[12.4260716  29.75734567  6.3668002   2.77462957  1.220961    1.15638352
   1.17451966  0.4310109 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[13.78515738 33.01203217  7.06315983  3.0781001   1.35450215  1.28286156
   1.30298066  0.47815212]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[13.81751657 33.0895247   7.07973982  3.08532559  1.3576817   1.28587294
   1.30603925  0.47927453]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[13.84987575 33.16701724  7.09631981  3.09255108  1.36086125  1.28888432
   1.30909785  0.48039694]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[13.88223494 33.24450977  7.1128998   3.09977657  1.3640408   1.29189571
   1.31215644  0.48151935]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[15.07952479 36.11173359  7.72635947  3.36711966  1.4816842   1.40331684
   1.42532446  0.52304852]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[15.11188398 36.18922613  7.74293946  3.37434515  1.48486375  1.40632822
   1.42838306  0.52417093]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[15.14424316 36.26671867  7.75951945  3.38157064  1.4880433   1.4093396
   1.43144165  0.52529334]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[15.17660235 36.3442112   7.77609944  3.38879612  1.49122285  1.41235098
   1.43450025  0.52641575]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.174

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[16.56804732 39.67639024  8.48903906  3.69949214  1.62794356  1.54184041
   1.56601984  0.57467937]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[16.6004065  39.75388277  8.50561905  3.70671763  1.63112311  1.54485179
   1.56907844  0.57580178]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[16.63276569 39.83137531  8.52219904  3.71394312  1.63430266  1.54786317
   1.57213703  0.57692419]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[16.66512487 39.90886784  8.53877903  3.72116861  1.63748221  1.55087455
   1.57519563  0.5780466 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[17.95949228 43.00856927  9.20197868  4.01018816  1.76466426  1.67132983
   1.69753943  0.622943  ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[17.99185147 43.08606181  9.21855867  4.01741365  1.76784381  1.67434121
   1.70059803  0.62406541]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[18.02421065 43.16355434  9.23513866  4.02463914  1.77102336  1.6773526
   1.70365662  0.62518782]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[18.05656984 43.24104688  9.25171865  4.03186463  1.77420291  1.68036398
   1.70671522  0.62631023]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.174

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[19.35093725 46.34074831  9.91491829  4.32088418  1.90138496  1.80081926
   1.82905903  0.67120663]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[19.38329643 46.41824084  9.93149828  4.32810967  1.90456451  1.80383064
   1.83211762  0.67232904]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[19.41565562 46.49573338  9.94807827  4.33533516  1.90774407  1.80684202
   1.83517622  0.67345145]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[19.44801481 46.57322592  9.96465827  4.34256065  1.91092362  1.8098534
   1.83823481  0.67457386]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.174

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[20.5482271  49.20797213 10.52837796  4.58822727  2.01902836  1.91224039
   1.94222705  0.7127358 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[20.58058629 49.28546467 10.54495795  4.59545276  2.02220791  1.91525177
   1.94528564  0.71385821]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[20.61294547 49.3629572  10.56153794  4.60267825  2.02538746  1.91826315
   1.94834424  0.71498062]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[20.64530466 49.44044974 10.57811794  4.60990374  2.02856701  1.92127453
   1.95140283  0.71610303]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[21.81023533 52.23018102 11.17499761  4.87002134  2.14303086  2.02968428
   2.06151226  0.75650978]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[21.84259451 52.30767356 11.19157761  4.87724683  2.14621041  2.03269567
   2.06457085  0.75763219]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[21.8749537  52.38516609 11.2081576   4.88447231  2.14938996  2.03570705
   2.06762945  0.7587546 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[21.90731289 52.46265863 11.22473759  4.8916978   2.15256951  2.03871843
   2.07068804  0.75987701]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[23.07224356 55.25238992 11.82161727  5.1518154   2.26703336  2.14712818
   2.18079747  0.80028377]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[23.10460274 55.32988245 11.83819726  5.15904089  2.27021291  2.15013956
   2.18385606  0.80140618]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[23.13696193 55.40737499 11.85477725  5.16626638  2.27339246  2.15315094
   2.18691466  0.80252859]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[23.16932111 55.48486752 11.87135724  5.17349187  2.27657201  2.15616233
   2.18997325  0.803651  ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[24.46368852 58.58456895 12.53455688  5.46251142  2.40375406  2.2766176
   2.31231706  0.8485474 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[24.49604771 58.66206149 12.55113687  5.46973691  2.40693361  2.27962899
   2.31537566  0.84966981]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[24.52840689 58.73955402 12.56771686  5.4769624   2.41011316  2.28264037
   2.31843425  0.85079222]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[24.56076608 58.81704656 12.58429686  5.48418789  2.41329271  2.28565175
   2.32149285  0.85191463]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.174

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[25.8227743  61.83925545 13.23091651  5.76598195  2.53729521  2.40309565
   2.44077806  0.89568862]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[25.85513349 61.91674799 13.2474965   5.77320744  2.54047476  2.40610703
   2.44383665  0.89681103]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[25.88749267 61.99424052 13.26407649  5.78043293  2.54365432  2.40911841
   2.44689525  0.89793344]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[25.91985186 62.07173306 13.28065648  5.78765842  2.54683387  2.41212979
   2.44995384  0.89905585]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[27.1495009  65.01644942 13.91069614  6.06222699  2.66765681  2.52656231
   2.56618046  0.94170742]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[27.18186008 65.09394195 13.92727613  6.06945248  2.67083637  2.52957369
   2.56923905  0.94282983]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[27.21421927 65.17143449 13.94385612  6.07667797  2.67401592  2.53258507
   2.57229765  0.94395224]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[27.24657845 65.24892702 13.96043611  6.08390346  2.67719547  2.53559645
   2.57535624  0.94507465]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[28.44386831 68.11615084 14.57389578  6.35124655  2.79483886  2.64701759
   2.68852426  0.98660382]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[28.47622749 68.19364338 14.59047577  6.35847204  2.79801842  2.65002897
   2.69158286  0.98772623]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[28.50858668 68.27113592 14.60705577  6.36569753  2.80119797  2.65304035
   2.69464145  0.98884864]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[28.54094587 68.34862845 14.62363576  6.37292302  2.80437752  2.65605173
   2.69770005  0.98997105]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[29.67351735 71.0608672  15.20393544  6.62581512  2.91566181  2.7614501
   2.80475088  1.0292554 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[29.70587653 71.13835974 15.22051544  6.63304061  2.91884136  2.76446148
   2.80780948  1.03037781]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[29.73823572 71.21585227 15.23709543  6.6402661   2.92202091  2.76747286
   2.81086807  1.03150022]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[29.77059491 71.29334481 15.25367542  6.64749159  2.92520047  2.77048425
   2.81392667  1.03262263]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.174

DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[30.96788476 74.16056863 15.86713509  6.91483468  3.04284386  2.88190538
   2.92709469  1.0741518 ]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[31.00024395 74.23806117 15.88371508  6.92206017  3.04602341  2.88491676
   2.93015328  1.07527421]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[31.03260313 74.3155537  15.90029507  6.92928566  3.04920296  2.88792814
   2.93321188  1.07639662]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17463429]
 [-0.16371648]
 [-0.15677214]
 [-0.05245633]]
W: 
[[31.06496232 74.39304624 15.91687506  6.93651114  3.05238252  2.89093952
   2.93627047  1.07751903]]
DW: 
[[-1.91771429]
 [-2.66678571]
 [-1.40914286]
 [-0.25614286]
 [-0.17

In [81]:
print(w)
final_test_pred = 1/(1+np.exp(-np.dot(w, features_test_list.T)+b))
y_ts_pred = predict(final_test_pred)
i = 0
while(i < 3378):
    print(y_ts_pred[0][i])
    i = i + 1


[[32.39168891 77.5702402  16.59665469  7.23275619  3.18274412  3.01440618
   3.06167287  1.12353783]]
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
